### ISSUE TITLE
Exact versions in `develop`/`mdeps`

### ISSUE THREAD

**Issue by maxim-ge** [scm4j/scm4j-releaser#4]
Normally coordinates in 'develop`/`mdeps` denotes SHAPSHOT version:
```
org.scm4j:scm4j-vcs-api:-SNAPSHOT
org.scm4j:scm4j-vcs-test:master-SNAPSHOT
```
In this case versions are changed when release branch is created:

`master-SNAPSHOT -> 4.0`
`-SNAPSHOT -> 4.0`
`1.0 -> 4.0`

**Comment by host6** [comment]
Done
