### ISSUE TITLE
Change password on GitHub issue

### ISSUE THREAD

**Issue by Kindratte** [scm4j/scm4j-releaser#59]
If github password changes, but credentials doesn't change, releaser fork throws not authorized exception. But when you pass correct credentials and trying to fork releaser throws EXECUTION FAILED: org.scm4j.vcs.api.exceptions.EVCSBranchExists: branch already exists: release/0.11.  remove releaser-vcs-workspaces fix this issue. 
Releaser version 0.30.0-SNAPSHOT

**Comment by host6** [comment]
Fixed by doing prune branches (also tags) in scm4j-vcs-git
