### ISSUE TITLE
Avoid !!omap in repositories parameters

### ISSUE THREAD

**Issue by maxim-ge** [scm4j/scm4j-releaser#9]
#12

**Comment by host6** [comment]
Clarify please: consider !!omap is present always?

**Comment by host6** [comment]
Following yaml is mapping, always considered as ordered map, !!omap is error:
```yaml
node3(.*):
  prop3: value3
```

Following yaml is sequence, !!omap will be prepended:
```yaml
- node3(.*):
    prop3: value3
```
Both sequence and mapping yamls are supported, both are ordered.
